version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rag-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend:/app
      - chroma_data:/app/chroma_db
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMA_DB_PATH=/app/chroma_db
      - APP_DEBUG=True
    networks:
      - rag-network
    depends_on:
      - chroma

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: ${BACKEND_URL:-http://localhost:8000}
    container_name: rag-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=/api
      - BACKEND_URL=${BACKEND_URL:-http://localhost:8000}
    networks:
      - rag-network
    depends_on:
      - backend

  chroma:
    build: ./chroma
    container_name: chroma-db
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - ALLOW_RESET=TRUE
      - CHROMA_SERVER_AUTH_CREDENTIALS=admin:admin
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge

volumes:
  chroma_data:
